"""user model add

Revision ID: 63f263221fac
Revises: a81d1662b2ff
Create Date: 2024-09-07 12:51:46.621434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f263221fac'
down_revision = 'a81d1662b2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('user_password', sa.String(length=300), nullable=True),
    sa.Column('user_email', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_model')
    # ### end Alembic commands ###
